### ISSUE TITLE
Drive Module

### ISSUE THREAD

**Issue by evanugarte** [SJSURobotics2019/missioncontrol2019#7]
This module is concerned with controlling the movement of the robot.
**Control:**
- Speed of each wheel
- Direction of each whieel
- Drive Modes: Drive, Rotate, Translate

**Feedback:**
- Compass heading
- Speed 
- Steering

**Comment by evanugarte** [comment]
I agree

**Comment by ariskoumis** [comment]
Joystick Requirements

Display the following values on your module:
Magnitude (0 -> 100%): Dictated by slider
Speed (0 -> 100%): Similar to magnitude, but takes into consideration if trigger is pressed
Brake (0/1): Inverse to value of trigger
Heading (0 -> 360): Dictated by direction of joystick
